export type MilestoneType = 'birthday' | 'gotcha_anniversary' | 'custom'

export interface PetMilestone {
  id: string
  petId: string
  familyId: string
  title: string
  date: string
  notes?: string
  autoGenerated: boolean
  milestoneType?: MilestoneType
  createdBy?: string
  createdAt: string
  updatedAt: string
}

export interface UpcomingMilestone extends PetMilestone {
  petName: string
  petAvatar?: string
  daysUntil: number
}

export const MILESTONE_TYPES: { value: MilestoneType; label: string }[] = [
  { value: 'birthday', label: 'Birthday' },
  { value: 'gotcha_anniversary', label: 'Gotcha Anniversary' },
  { value: 'custom', label: 'Custom' },
]
