# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "imgtnixyralpdrmedwzi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.media-proxy]
verify_jwt = true

[functions.elevenlabs-tts]
verify_jwt = true

[functions.document-viewer]
verify_jwt = false

[functions.transcribe]
verify_jwt = true

[functions.export-enhanced]
verify_jwt = true

[functions.rtbf-analyze]
verify_jwt = true

[functions.rtbf-execute]
verify_jwt = true

[functions.invite-link]
verify_jwt = true

[functions.invite-validate]
verify_jwt = false

[functions.family-codes]
verify_jwt = true

[functions.join-by-code]
verify_jwt = true

[functions.family-requests]
verify_jwt = false

[functions.families-preflight]
verify_jwt = false

[functions.families-verify]
verify_jwt = true

[functions.families-merge]
verify_jwt = false

[functions.families-suggest-merge]
verify_jwt = false

[functions.families-claim-admin]
verify_jwt = false

[functions.collision-detector]
verify_jwt = false

[functions.setup-qa-family]
verify_jwt = false

[functions.seed-qa-data]
verify_jwt = true

[functions.qa-seed-status]
verify_jwt = true

[db]
# Port to use for the local database URL.
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

# Email testing server. Emails sent with the local dev setup are not actually sent - instead, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://127.0.0.1:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://127.0.0.1:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email
# addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false