// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imgtnixyralpdrmedwzi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZ3RuaXh5cmFscGRybWVkd3ppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDUwMDcsImV4cCI6MjA3MzAyMTAwN30.225nrhTEXlH1rwuwTDvjCivC5TWzm0yZV-47l8T099U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});